### ISSUE TITLE
Reverse chains

### ISSUE THREAD

**Issue by tobyink** [bk2204/muter#1]
Would be handy if as well as these two being the reverse of each other:

    muter -c 'foo:bar:baz'
    muter -c '-baz:-bar:-foo'

There was the ability to do this:

    muter -r -c 'foo:bar:baz'

This would be pretty simple to do. Accept an "-r" flag which determines that the chain should be reversed, then instantiate App::Muter::Chain like `App::Muter::Chain->new($chain, $is_reversed)`. Then when parsing the chain do something like:

```
if ($is_reversed) {
  @chain =
    reverse
    map { $_->{method} = ($_->{method} eq 'encode' ? 'decode' : 'encode'); $_ }
    @chain;
}
```

**Comment by bk2204** [comment]
That does sound like it could be useful.  As with any new feature, I'd like to think about it for a few days before making a commitment, but it's definitely a possibility in a future version.

**Comment by bk2204** [comment]
I've pushed an implementation of this to the repository and will tag 0.2.0 with it.
