### ISSUE TITLE
"1" is invalid argument to binmode; also add binmode on output handle

### ISSUE THREAD

**Issue by vadim-160102** [bk2204/muter#3]
Please see https://metacpan.org/release/App-Muter/source/lib/App/Muter.pm#L102

As it stands, this line is a no-op, and Perl doesn't issue a warning, because it's written as method call; should be "$io->binmode();". To help Win32 users, add "$stdout->binmode();" into the same subroutine.

**Comment by bk2204** [comment]
Thanks for the report.  I've fixed it in the `perl` branch.  Be aware that most current development is on the Rust version, a release of which will likely be coming this weekend.
